import './globals.css'
import Header from '@/components/layout/header';
import Footer from '@/components/layout/footer';
import 'bootstrap/dist/css/bootstrap.min.css';
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import LoginButton from '@/components/layout/loginButton';


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Movie--Picker',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {


  return (
    <html lang="en">
     
      <body className={inter.className}>
      <LoginButton />
         <Header/>
        {children}
        <Footer/>
     
        </body>
    </html>
  )
}
